"""empty message

Revision ID: 5d4e2c7ffb47
Revises: 709723b37b83
Create Date: 2025-01-09 13:51:45.774027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4e2c7ffb47'
down_revision = '709723b37b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynamic_challenge', sa.Column('function', sa.String(length=32), nullable=True))
    op.drop_constraint('dynamic_challenge_ibfk_1', 'dynamic_challenge', type_='foreignkey')
    op.create_foreign_key(None, 'dynamic_challenge', 'challenges', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dynamic_challenge', type_='foreignkey')
    op.create_foreign_key('dynamic_challenge_ibfk_1', 'dynamic_challenge', 'challenges', ['id'], ['id'])
    op.drop_column('dynamic_challenge', 'function')
    # ### end Alembic commands ###
