"""empty message

Revision ID: bbaba6cd292f
Revises: e17978635832
Create Date: 2025-02-25 15:42:02.647880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbaba6cd292f'
down_revision = 'e17978635832'
branch_labels = None
depends_on = None


def upgrade():
        # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
    sa.Column('actionId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actionType', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actionDetail', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('actionTime', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='userId'),
    sa.PrimaryKeyConstraint('actionId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_logs')
    # ### end Alembic commands ###
