"""empty message

Revision ID: e17978635832
Revises: 50b52f907c49
Create Date: 2025-02-25 15:34:01.401746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e17978635832'
down_revision = '50b52f907c49'
branch_labels = None
depends_on = None


def upgrade():
        # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
    sa.Column('actionId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actionDate', mysql.DATETIME(), nullable=False),
    sa.Column('actionType', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actionDetail', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='userId', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('actionId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_logs')
    # ### end Alembic commands ###
